recipe: default.v1
language: en
pipeline:
- name: LLMCommandGenerator
  # flow_retrieval:
  #   active: false
  llm:
    #model_name: gpt-3.5-turbo
    model_name: gpt-4-turbo
    #model_name: gpt-4



policies:
  - name: FlowPolicy
  #- name: rasa_plus.ml.EnterpriseSearchPolicy
  # vector_store:
  #   type: "faiss"
  #   source: "./docs"
  # llm:
  #   model_name: gpt-4-turbo
  #- name: rasa_plus.ml.IntentlessPolicy
  - name: EnterpriseSearchPolicy
  - name: IntentlessPolicy
    nlu_abstention_threshold: 0.6

assistant_id: 20240408-145223-unsorted-callable
